apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-buffer-size: "12k"
spec:
# Added ssl certificate
  tls:
  - hosts:
      - https-botswanaemrdev.intellisoftkenya.com
    secretName: ocl-tls
  rules:
  - host: botswanaemrdev.intellisoftkenya.com
    http:
      paths:
      # Auth service
      - path: /oclapi(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: oclapiservice
            port:
              number: 8000
      # File storage service
      - path: /oclweb(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: oclwebservice
            port:
              number: 4000
                  
